name: 'olist_lakehouse'
version: '1.0.0'
profile: 'default'

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  olist_lakehouse:
    gold:
      +materialized: table
      +schema: gold